"""Observability contracts owned by the application boundary."""
from __future__ import annotations

from typing import Any, Protocol


class RuntimeMetricsPort(Protocol):
    def begin(self, **values: Any) -> None: ...
    def mark(self, trace_id: str, stage: str, **values: Any) -> bool: ...
    def confirm_playback(self, **values: Any) -> bool: ...
    def snapshot(self) -> dict[str, Any]: ...


class StructuredLoggerPort(Protocol):
    def emit(self, event: str, component: str, **fields: Any) -> dict: ...
