<# Safe, idempotent installation readiness and local configuration entrypoint. #>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [ValidateSet('audit', 'prepare', 'verify')]
    [string]$Action = 'audit',
    [string]$WorkspaceWin = 'C:\workSpace\cyberWife',
    [string]$WorkspaceWsl = '/mnt/c/workSpace/cyberWife',
    [string]$WslHome = '',
    [string]$LlamaCppPath = 'C:\tools\llama.cpp\llama-server.exe',
    [string]$LlamaModelPath = 'C:\ComfyUI-aki-v2\ComfyUI\models\LLM\Qwen3-14B-Q4_K_M.gguf',
    [string]$AvatarModelWsl = '/mnt/c/ComfyUI-aki-v2/ComfyUI/models/Audio/wav2lip/wav2lip.pth',
    [string]$ReportPath = ''
)

$ErrorActionPreference = 'Stop'
$checks = [System.Collections.Generic.List[object]]::new()

function Add-Check([string]$Name, [bool]$Pass, [string]$Detail, [bool]$Required = $true) {
    $checks.Add([pscustomobject][ordered]@{ name = $Name; pass = $Pass; required = $Required; detail = $Detail })
}

function Test-WslPath([string]$Path, [string]$Kind = 'e') {
    & wsl.exe sh -lc "test -$Kind '$Path'"
    return ($LASTEXITCODE -eq 0)
}

$wslCommand = Get-Command wsl.exe -ErrorAction SilentlyContinue
Add-Check 'windows.wsl' ($null -ne $wslCommand) 'wsl.exe must be installed and callable'
if ($wslCommand -and [string]::IsNullOrWhiteSpace($WslHome)) {
    $WslHome = ((& wsl.exe sh -lc 'printf %s "$HOME"') | Out-String).Trim()
}
Add-Check 'wsl.home' (-not [string]::IsNullOrWhiteSpace($WslHome) -and $WslHome.StartsWith('/')) $WslHome
$dataRoot = if ($WslHome) { "$WslHome/.cyberWife" } else { '' }

Add-Check 'windows.workspace' (Test-Path -LiteralPath $WorkspaceWin -PathType Container) $WorkspaceWin
Add-Check 'windows.llama_binary' (Test-Path -LiteralPath $LlamaCppPath -PathType Leaf) $LlamaCppPath
Add-Check 'windows.llama_model' (Test-Path -LiteralPath $LlamaModelPath -PathType Leaf) $LlamaModelPath
Add-Check 'windows.nvidia_smi' ($null -ne (Get-Command nvidia-smi.exe -ErrorAction SilentlyContinue)) 'NVIDIA driver CLI'

if ($wslCommand -and $WslHome) {
    Add-Check 'wsl.workspace' (Test-WslPath $WorkspaceWsl 'd') $WorkspaceWsl
    Add-Check 'wsl.cosy_python' (Test-WslPath "$dataRoot/venvs/cosyvoice/bin/python" 'x') "$dataRoot/venvs/cosyvoice/bin/python"
    Add-Check 'wsl.avatar_python' (Test-WslPath "$dataRoot/venvs/avatar-v1-py312/bin/python" 'x') "$dataRoot/venvs/avatar-v1-py312/bin/python"
    Add-Check 'wsl.cosy_source' (Test-WslPath "$dataRoot/src/CosyVoice" 'd') "$dataRoot/src/CosyVoice"
    Add-Check 'wsl.avatar_model' (Test-WslPath $AvatarModelWsl 'f') $AvatarModelWsl
    Add-Check 'release.frontend' (Test-WslPath "$WorkspaceWsl/prototype/dist/index.html" 'f') "$WorkspaceWsl/prototype/dist/index.html"
    Add-Check 'release.model_registry' (Test-WslPath "$WorkspaceWsl/config/model-registry.local.yaml" 'f') "$WorkspaceWsl/config/model-registry.local.yaml"
}

if ($Action -eq 'prepare') {
    if (-not $WslHome) { throw 'cannot prepare without a resolved WSL home' }
    if ($PSCmdlet.ShouldProcess($dataRoot, 'create private runtime directories')) {
        & wsl.exe sh -lc "umask 077; mkdir -p '$dataRoot/assets/portrait' '$dataRoot/assets/voice' '$dataRoot/logs' '$dataRoot/audit' '$dataRoot/avatar/avatars'"
        if ($LASTEXITCODE -ne 0) { throw 'failed to create WSL private runtime directories' }
    }
    $runtimeConfig = Join-Path $WorkspaceWin 'config\runtime.local.toml'
    if (-not (Test-Path -LiteralPath $runtimeConfig)) {
        $content = @"
# Generated by Install-CyberWife.ps1; private local paths only.
[paths]
assets_root = "$dataRoot/assets"
data_root = "$dataRoot"
logs_root = "$dataRoot/logs"
salt_file = "$dataRoot/audit/.salt"
cosyvoice_source = "$dataRoot/src/CosyVoice"

[db]
path = "$dataRoot/cyberwife.db"
wal = true
cache_size_kb = 2048
synchronous = "NORMAL"

[models]
tts = "cosyvoice2-0.5b"
"@
        if ($PSCmdlet.ShouldProcess($runtimeConfig, 'create missing runtime config')) {
            Set-Content -LiteralPath $runtimeConfig -Value $content -Encoding UTF8 -NoNewline
        }
    }
}

$requiredFailures = @($checks | Where-Object { $_.required -and -not $_.pass })
$result = [pscustomobject][ordered]@{
    schema_version = 1
    action = $Action
    workspace_windows = $WorkspaceWin
    workspace_wsl = $WorkspaceWsl
    wsl_home = $WslHome
    data_root_wsl = $dataRoot
    checks = @($checks)
    required_failure_count = $requiredFailures.Count
    ready = ($requiredFailures.Count -eq 0)
}
if ($ReportPath) {
    $parent = Split-Path -Parent $ReportPath
    if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
    $result | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $ReportPath -Encoding UTF8
}
$result | ConvertTo-Json -Depth 6
if (-not $result.ready) { exit 2 }
